import type { GarmentType } from '../../types'

export const trousers: GarmentType = {
  id: 'trousers',
  categoryId: 'bottoms',
  nameKey: 'garments.bottoms.trousers.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'fit',
      nameKey: 'parts.fit.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'regular',
      variants: [
        { id: 'slim', nameKey: 'parts.fit.variants.slim', svgPath: '' },
        { id: 'regular', nameKey: 'parts.fit.variants.regular', svgPath: '' },
        { id: 'relaxed', nameKey: 'parts.fit.variants.relaxed', svgPath: '' },
        { id: 'oversized', nameKey: 'parts.fit.variants.oversized', svgPath: '' },
      ],
    },
    {
      id: 'waistband',
      nameKey: 'parts.waistband.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.waistband.variants.standard', svgPath: '' },
        { id: 'high', nameKey: 'parts.waistband.variants.high', svgPath: '' },
        { id: 'low', nameKey: 'parts.waistband.variants.low', svgPath: '' },
        { id: 'elastic', nameKey: 'parts.waistband.variants.elastic', svgPath: '' },
      ],
    },
    {
      id: 'rise',
      nameKey: 'parts.rise.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'mid',
      variants: [
        { id: 'high', nameKey: 'parts.rise.variants.high', svgPath: '' },
        { id: 'mid', nameKey: 'parts.rise.variants.mid', svgPath: '' },
        { id: 'low', nameKey: 'parts.rise.variants.low', svgPath: '' },
        { id: 'ultra-high', nameKey: 'parts.rise.variants.ultra-high', svgPath: '' },
      ],
    },
    {
      id: 'leg-shape',
      nameKey: 'parts.leg-shape.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.leg-shape.variants.straight', svgPath: '' },
        { id: 'tapered', nameKey: 'parts.leg-shape.variants.tapered', svgPath: '' },
        { id: 'wide', nameKey: 'parts.leg-shape.variants.wide', svgPath: '' },
        { id: 'bootcut', nameKey: 'parts.leg-shape.variants.bootcut', svgPath: '' },
        { id: 'flared', nameKey: 'parts.leg-shape.variants.flared', svgPath: '' },
        { id: 'slim', nameKey: 'parts.leg-shape.variants.slim', svgPath: '' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: '' },
        { id: 'cuffed', nameKey: 'parts.hem.variants.cuffed', svgPath: '' },
        { id: 'cropped', nameKey: 'parts.hem.variants.cropped', svgPath: '' },
        { id: 'raw', nameKey: 'parts.hem.variants.raw', svgPath: '' },
      ],
    },
    {
      id: 'fly',
      nameKey: 'parts.fly.name',
      required: true,
      layerOrder: 2,
      defaultVariantId: 'zipper',
      variants: [
        { id: 'zipper', nameKey: 'parts.fly.variants.zipper', svgPath: '' },
        { id: 'button', nameKey: 'parts.fly.variants.button', svgPath: '' },
        { id: 'drawstring', nameKey: 'parts.fly.variants.drawstring', svgPath: '' },
      ],
    },
    {
      id: 'pockets',
      nameKey: 'parts.pockets.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'slash',
      variants: [
        { id: 'slash', nameKey: 'parts.pockets.variants.slash', svgPath: '' },
        { id: 'welt', nameKey: 'parts.pockets.variants.welt', svgPath: '' },
        { id: 'patch', nameKey: 'parts.pockets.variants.patch', svgPath: '' },
        { id: 'cargo', nameKey: 'parts.pockets.variants.cargo', svgPath: '' },
        { id: 'none', nameKey: 'parts.pockets.variants.none', svgPath: '' },
      ],
    },
    {
      id: 'pleat-type',
      nameKey: 'parts.pleat-type.name',
      required: false,
      layerOrder: 1,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.pleat-type.variants.none', svgPath: '' },
        { id: 'single', nameKey: 'parts.pleat-type.variants.single', svgPath: '' },
        { id: 'double', nameKey: 'parts.pleat-type.variants.double', svgPath: '' },
        { id: 'inverted', nameKey: 'parts.pleat-type.variants.inverted', svgPath: '' },
      ],
    },
  ],
}
