import type { GarmentType } from '../../types'

export const trousers: GarmentType = {
  id: 'trousers',
  categoryId: 'bottoms',
  nameKey: 'garments.bottoms.trousers.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'fit',
      nameKey: 'parts.fit.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'regular',
      variants: [
        { id: 'slim', nameKey: 'parts.fit.variants.slim', svgPath: 'bottoms/trousers/fit/slim.svg' },
        { id: 'regular', nameKey: 'parts.fit.variants.regular', svgPath: 'bottoms/trousers/fit/regular.svg' },
        { id: 'relaxed', nameKey: 'parts.fit.variants.relaxed', svgPath: 'bottoms/trousers/fit/relaxed.svg' },
        { id: 'oversized', nameKey: 'parts.fit.variants.oversized', svgPath: 'bottoms/trousers/fit/oversized.svg' },
      ],
    },
    {
      id: 'waistband',
      nameKey: 'parts.waistband.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.waistband.variants.standard', svgPath: 'bottoms/trousers/waistband/standard.svg' },
        { id: 'high', nameKey: 'parts.waistband.variants.high', svgPath: 'bottoms/trousers/waistband/high.svg' },
        { id: 'low', nameKey: 'parts.waistband.variants.low', svgPath: 'bottoms/trousers/waistband/low.svg' },
        { id: 'elastic', nameKey: 'parts.waistband.variants.elastic', svgPath: 'bottoms/trousers/waistband/elastic.svg' },
      ],
    },
    {
      id: 'rise',
      nameKey: 'parts.rise.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'mid',
      variants: [
        { id: 'high', nameKey: 'parts.rise.variants.high', svgPath: 'bottoms/trousers/rise/high.svg' },
        { id: 'mid', nameKey: 'parts.rise.variants.mid', svgPath: 'bottoms/trousers/rise/mid.svg' },
        { id: 'low', nameKey: 'parts.rise.variants.low', svgPath: 'bottoms/trousers/rise/low.svg' },
        { id: 'ultra-high', nameKey: 'parts.rise.variants.ultra-high', svgPath: 'bottoms/trousers/rise/ultra-high.svg' },
      ],
    },
    {
      id: 'leg-shape',
      nameKey: 'parts.leg-shape.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.leg-shape.variants.straight', svgPath: 'bottoms/trousers/leg-shape/straight.svg' },
        { id: 'tapered', nameKey: 'parts.leg-shape.variants.tapered', svgPath: 'bottoms/trousers/leg-shape/tapered.svg' },
        { id: 'wide', nameKey: 'parts.leg-shape.variants.wide', svgPath: 'bottoms/trousers/leg-shape/wide.svg' },
        { id: 'bootcut', nameKey: 'parts.leg-shape.variants.bootcut', svgPath: 'bottoms/trousers/leg-shape/bootcut.svg' },
        { id: 'flared', nameKey: 'parts.leg-shape.variants.flared', svgPath: 'bottoms/trousers/leg-shape/flared.svg' },
        { id: 'slim', nameKey: 'parts.leg-shape.variants.slim', svgPath: 'bottoms/trousers/leg-shape/slim.svg' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: 'bottoms/trousers/hem/straight.svg' },
        { id: 'cuffed', nameKey: 'parts.hem.variants.cuffed', svgPath: 'bottoms/trousers/hem/cuffed.svg' },
        { id: 'cropped', nameKey: 'parts.hem.variants.cropped', svgPath: 'bottoms/trousers/hem/cropped.svg' },
        { id: 'raw', nameKey: 'parts.hem.variants.raw', svgPath: 'bottoms/trousers/hem/raw.svg' },
      ],
    },
    {
      id: 'fly',
      nameKey: 'parts.fly.name',
      required: true,
      layerOrder: 2,
      defaultVariantId: 'zipper',
      variants: [
        { id: 'zipper', nameKey: 'parts.fly.variants.zipper', svgPath: 'bottoms/trousers/fly/zipper.svg' },
        { id: 'button', nameKey: 'parts.fly.variants.button', svgPath: 'bottoms/trousers/fly/button.svg' },
        { id: 'drawstring', nameKey: 'parts.fly.variants.drawstring', svgPath: 'bottoms/trousers/fly/drawstring.svg' },
      ],
    },
    {
      id: 'pockets',
      nameKey: 'parts.pockets.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'slash',
      variants: [
        { id: 'slash', nameKey: 'parts.pockets.variants.slash', svgPath: 'bottoms/trousers/pockets/slash.svg' },
        { id: 'welt', nameKey: 'parts.pockets.variants.welt', svgPath: 'bottoms/trousers/pockets/welt.svg' },
        { id: 'patch', nameKey: 'parts.pockets.variants.patch', svgPath: 'bottoms/trousers/pockets/patch.svg' },
        { id: 'cargo', nameKey: 'parts.pockets.variants.cargo', svgPath: 'bottoms/trousers/pockets/cargo.svg' },
        { id: 'none', nameKey: 'parts.pockets.variants.none', svgPath: 'bottoms/trousers/pockets/none.svg' },
      ],
    },
    {
      id: 'pleat-type',
      nameKey: 'parts.pleat-type.name',
      required: false,
      layerOrder: 1,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.pleat-type.variants.none', svgPath: 'bottoms/trousers/pleat-type/none.svg' },
        { id: 'single', nameKey: 'parts.pleat-type.variants.single', svgPath: 'bottoms/trousers/pleat-type/single.svg' },
        { id: 'double', nameKey: 'parts.pleat-type.variants.double', svgPath: 'bottoms/trousers/pleat-type/double.svg' },
        { id: 'inverted', nameKey: 'parts.pleat-type.variants.inverted', svgPath: 'bottoms/trousers/pleat-type/inverted.svg' },
      ],
    },
  ],
}
