import type { GarmentType } from '../../types'

export const aLineDress: GarmentType = {
  id: 'a-line-dress',
  categoryId: 'dresses',
  nameKey: 'garments.dresses.a-line-dress.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'bodice',
      nameKey: 'parts.bodice.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'fitted',
      variants: [
        { id: 'fitted', nameKey: 'parts.bodice.variants.fitted', svgPath: '' },
        { id: 'relaxed', nameKey: 'parts.bodice.variants.relaxed', svgPath: '' },
        { id: 'structured', nameKey: 'parts.bodice.variants.structured', svgPath: '' },
        { id: 'draped', nameKey: 'parts.bodice.variants.draped', svgPath: '' },
      ],
    },
    {
      id: 'waistline',
      nameKey: 'parts.waistline.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'natural',
      variants: [
        { id: 'natural', nameKey: 'parts.waistline.variants.natural', svgPath: '' },
        { id: 'empire', nameKey: 'parts.waistline.variants.empire', svgPath: '' },
        { id: 'drop', nameKey: 'parts.waistline.variants.drop', svgPath: '' },
        { id: 'cinched', nameKey: 'parts.waistline.variants.cinched', svgPath: '' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: '' },
        { id: 'ruffled', nameKey: 'parts.hem.variants.ruffled', svgPath: '' },
        { id: 'asymmetric', nameKey: 'parts.hem.variants.asymmetric', svgPath: '' },
      ],
    },
    {
      id: 'skirt-length',
      nameKey: 'parts.skirt-length.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'knee',
      variants: [
        { id: 'mini', nameKey: 'parts.skirt-length.variants.mini', svgPath: '' },
        { id: 'knee', nameKey: 'parts.skirt-length.variants.knee', svgPath: '' },
        { id: 'midi', nameKey: 'parts.skirt-length.variants.midi', svgPath: '' },
        { id: 'maxi', nameKey: 'parts.skirt-length.variants.maxi', svgPath: '' },
        { id: 'tea-length', nameKey: 'parts.skirt-length.variants.tea-length', svgPath: '' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'round',
      variants: [
        { id: 'round', nameKey: 'parts.neckline.variants.round', svgPath: '' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: '' },
        { id: 'scoop', nameKey: 'parts.neckline.variants.scoop', svgPath: '' },
        { id: 'square', nameKey: 'parts.neckline.variants.square', svgPath: '' },
        { id: 'boat', nameKey: 'parts.neckline.variants.boat', svgPath: '' },
        { id: 'sweetheart', nameKey: 'parts.neckline.variants.sweetheart', svgPath: '' },
        { id: 'halter', nameKey: 'parts.neckline.variants.halter', svgPath: '' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: '' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'short',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: '' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: '' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: '' },
        { id: 'puff', nameKey: 'parts.sleeves.variants.puff', svgPath: '' },
        { id: 'bishop', nameKey: 'parts.sleeves.variants.bishop', svgPath: '' },
        { id: 'bell', nameKey: 'parts.sleeves.variants.bell', svgPath: '' },
        { id: 'cap', nameKey: 'parts.sleeves.variants.cap', svgPath: '' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: '' },
      ],
    },
  ],
}
