import type { GarmentType } from '../../types'

export const aLineDress: GarmentType = {
  id: 'a-line-dress',
  categoryId: 'dresses',
  nameKey: 'garments.dresses.a-line-dress.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'bodice',
      nameKey: 'parts.bodice.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'fitted',
      variants: [
        { id: 'fitted', nameKey: 'parts.bodice.variants.fitted', svgPath: 'dresses/a-line-dress/bodice/fitted.svg' },
        { id: 'relaxed', nameKey: 'parts.bodice.variants.relaxed', svgPath: 'dresses/a-line-dress/bodice/relaxed.svg' },
        { id: 'structured', nameKey: 'parts.bodice.variants.structured', svgPath: 'dresses/a-line-dress/bodice/structured.svg' },
        { id: 'draped', nameKey: 'parts.bodice.variants.draped', svgPath: 'dresses/a-line-dress/bodice/draped.svg' },
      ],
    },
    {
      id: 'waistline',
      nameKey: 'parts.waistline.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'natural',
      variants: [
        { id: 'natural', nameKey: 'parts.waistline.variants.natural', svgPath: 'dresses/a-line-dress/waistline/natural.svg' },
        { id: 'empire', nameKey: 'parts.waistline.variants.empire', svgPath: 'dresses/a-line-dress/waistline/empire.svg' },
        { id: 'drop', nameKey: 'parts.waistline.variants.drop', svgPath: 'dresses/a-line-dress/waistline/drop.svg' },
        { id: 'cinched', nameKey: 'parts.waistline.variants.cinched', svgPath: 'dresses/a-line-dress/waistline/cinched.svg' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: 'dresses/a-line-dress/hem/straight.svg' },
        { id: 'ruffled', nameKey: 'parts.hem.variants.ruffled', svgPath: 'dresses/a-line-dress/hem/ruffled.svg' },
        { id: 'asymmetric', nameKey: 'parts.hem.variants.asymmetric', svgPath: 'dresses/a-line-dress/hem/asymmetric.svg' },
      ],
    },
    {
      id: 'skirt-length',
      nameKey: 'parts.skirt-length.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'knee',
      variants: [
        { id: 'mini', nameKey: 'parts.skirt-length.variants.mini', svgPath: 'dresses/a-line-dress/skirt-length/mini.svg' },
        { id: 'knee', nameKey: 'parts.skirt-length.variants.knee', svgPath: 'dresses/a-line-dress/skirt-length/knee.svg' },
        { id: 'midi', nameKey: 'parts.skirt-length.variants.midi', svgPath: 'dresses/a-line-dress/skirt-length/midi.svg' },
        { id: 'maxi', nameKey: 'parts.skirt-length.variants.maxi', svgPath: 'dresses/a-line-dress/skirt-length/maxi.svg' },
        { id: 'tea-length', nameKey: 'parts.skirt-length.variants.tea-length', svgPath: 'dresses/a-line-dress/skirt-length/tea-length.svg' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'round',
      variants: [
        { id: 'round', nameKey: 'parts.neckline.variants.round', svgPath: 'dresses/a-line-dress/neckline/round.svg' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: 'dresses/a-line-dress/neckline/v-neck.svg' },
        { id: 'scoop', nameKey: 'parts.neckline.variants.scoop', svgPath: 'dresses/a-line-dress/neckline/scoop.svg' },
        { id: 'square', nameKey: 'parts.neckline.variants.square', svgPath: 'dresses/a-line-dress/neckline/square.svg' },
        { id: 'boat', nameKey: 'parts.neckline.variants.boat', svgPath: 'dresses/a-line-dress/neckline/boat.svg' },
        { id: 'sweetheart', nameKey: 'parts.neckline.variants.sweetheart', svgPath: 'dresses/a-line-dress/neckline/sweetheart.svg' },
        { id: 'halter', nameKey: 'parts.neckline.variants.halter', svgPath: 'dresses/a-line-dress/neckline/halter.svg' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: 'dresses/a-line-dress/neckline/off-shoulder.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'short',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: 'dresses/a-line-dress/sleeves/long.svg' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: 'dresses/a-line-dress/sleeves/short.svg' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: 'dresses/a-line-dress/sleeves/three-quarter.svg' },
        { id: 'puff', nameKey: 'parts.sleeves.variants.puff', svgPath: 'dresses/a-line-dress/sleeves/puff.svg' },
        { id: 'bishop', nameKey: 'parts.sleeves.variants.bishop', svgPath: 'dresses/a-line-dress/sleeves/bishop.svg' },
        { id: 'bell', nameKey: 'parts.sleeves.variants.bell', svgPath: 'dresses/a-line-dress/sleeves/bell.svg' },
        { id: 'cap', nameKey: 'parts.sleeves.variants.cap', svgPath: 'dresses/a-line-dress/sleeves/cap.svg' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: 'dresses/a-line-dress/sleeves/sleeveless.svg' },
      ],
    },
  ],
}
