import type { GarmentType } from '../../types'

export const cocktailDress: GarmentType = {
  id: 'cocktail-dress',
  categoryId: 'dresses',
  nameKey: 'garments.dresses.cocktail-dress.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'bodice',
      nameKey: 'parts.bodice.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'fitted',
      variants: [
        { id: 'fitted', nameKey: 'parts.bodice.variants.fitted', svgPath: 'dresses/cocktail-dress/bodice/fitted.svg' },
        { id: 'corset', nameKey: 'parts.bodice.variants.corset', svgPath: 'dresses/cocktail-dress/bodice/corset.svg' },
        { id: 'draped', nameKey: 'parts.bodice.variants.draped', svgPath: 'dresses/cocktail-dress/bodice/draped.svg' },
        { id: 'structured', nameKey: 'parts.bodice.variants.structured', svgPath: 'dresses/cocktail-dress/bodice/structured.svg' },
      ],
    },
    {
      id: 'skirt-shape',
      nameKey: 'parts.skirt-shape.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'a-line',
      variants: [
        { id: 'a-line', nameKey: 'parts.skirt-shape.variants.a-line', svgPath: 'dresses/cocktail-dress/skirt-shape/a-line.svg' },
        { id: 'fit-and-flare', nameKey: 'parts.skirt-shape.variants.fit-and-flare', svgPath: 'dresses/cocktail-dress/skirt-shape/fit-and-flare.svg' },
        { id: 'straight', nameKey: 'parts.skirt-shape.variants.straight', svgPath: 'dresses/cocktail-dress/skirt-shape/straight.svg' },
        { id: 'bubble', nameKey: 'parts.skirt-shape.variants.bubble', svgPath: 'dresses/cocktail-dress/skirt-shape/bubble.svg' },
      ],
    },
    {
      id: 'length',
      nameKey: 'parts.length.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'above-knee',
      variants: [
        { id: 'above-knee', nameKey: 'parts.length.variants.above-knee', svgPath: 'dresses/cocktail-dress/length/above-knee.svg' },
        { id: 'knee', nameKey: 'parts.length.variants.knee', svgPath: 'dresses/cocktail-dress/length/knee.svg' },
        { id: 'tea-length', nameKey: 'parts.length.variants.tea-length', svgPath: 'dresses/cocktail-dress/length/tea-length.svg' },
      ],
    },
    {
      id: 'back',
      nameKey: 'parts.back.name',
      required: false,
      layerOrder: 1,
      defaultVariantId: 'standard',
      variants: [
        { id: 'open', nameKey: 'parts.back.variants.open', svgPath: 'dresses/cocktail-dress/back/open.svg' },
        { id: 'low', nameKey: 'parts.back.variants.low', svgPath: 'dresses/cocktail-dress/back/low.svg' },
        { id: 'keyhole', nameKey: 'parts.back.variants.keyhole', svgPath: 'dresses/cocktail-dress/back/keyhole.svg' },
        { id: 'standard', nameKey: 'parts.back.variants.standard', svgPath: 'dresses/cocktail-dress/back/standard.svg' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'sweetheart',
      variants: [
        { id: 'sweetheart', nameKey: 'parts.neckline.variants.sweetheart', svgPath: 'dresses/cocktail-dress/neckline/sweetheart.svg' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: 'dresses/cocktail-dress/neckline/v-neck.svg' },
        { id: 'boat', nameKey: 'parts.neckline.variants.boat', svgPath: 'dresses/cocktail-dress/neckline/boat.svg' },
        { id: 'strapless', nameKey: 'parts.neckline.variants.strapless', svgPath: 'dresses/cocktail-dress/neckline/strapless.svg' },
        { id: 'halter', nameKey: 'parts.neckline.variants.halter', svgPath: 'dresses/cocktail-dress/neckline/halter.svg' },
        { id: 'one-shoulder', nameKey: 'parts.neckline.variants.one-shoulder', svgPath: 'dresses/cocktail-dress/neckline/one-shoulder.svg' },
        { id: 'scoop', nameKey: 'parts.neckline.variants.scoop', svgPath: 'dresses/cocktail-dress/neckline/scoop.svg' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: 'dresses/cocktail-dress/neckline/off-shoulder.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'sleeveless',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: 'dresses/cocktail-dress/sleeves/long.svg' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: 'dresses/cocktail-dress/sleeves/short.svg' },
        { id: 'cap', nameKey: 'parts.sleeves.variants.cap', svgPath: 'dresses/cocktail-dress/sleeves/cap.svg' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: 'dresses/cocktail-dress/sleeves/sleeveless.svg' },
        { id: 'off-shoulder', nameKey: 'parts.sleeves.variants.off-shoulder', svgPath: 'dresses/cocktail-dress/sleeves/off-shoulder.svg' },
      ],
    },
  ],
}
