import type { GarmentType } from '../../types'

export const maxiDress: GarmentType = {
  id: 'maxi-dress',
  categoryId: 'dresses',
  nameKey: 'garments.dresses.maxi-dress.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'bodice',
      nameKey: 'parts.bodice.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'fitted',
      variants: [
        { id: 'fitted', nameKey: 'parts.bodice.variants.fitted', svgPath: 'dresses/maxi-dress/bodice/fitted.svg' },
        { id: 'relaxed', nameKey: 'parts.bodice.variants.relaxed', svgPath: 'dresses/maxi-dress/bodice/relaxed.svg' },
        { id: 'empire', nameKey: 'parts.bodice.variants.empire', svgPath: 'dresses/maxi-dress/bodice/empire.svg' },
        { id: 'smocked', nameKey: 'parts.bodice.variants.smocked', svgPath: 'dresses/maxi-dress/bodice/smocked.svg' },
      ],
    },
    {
      id: 'waistline',
      nameKey: 'parts.waistline.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'natural',
      variants: [
        { id: 'natural', nameKey: 'parts.waistline.variants.natural', svgPath: 'dresses/maxi-dress/waistline/natural.svg' },
        { id: 'empire', nameKey: 'parts.waistline.variants.empire', svgPath: 'dresses/maxi-dress/waistline/empire.svg' },
        { id: 'drop', nameKey: 'parts.waistline.variants.drop', svgPath: 'dresses/maxi-dress/waistline/drop.svg' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: 'dresses/maxi-dress/hem/straight.svg' },
        { id: 'ruffled', nameKey: 'parts.hem.variants.ruffled', svgPath: 'dresses/maxi-dress/hem/ruffled.svg' },
        { id: 'handkerchief', nameKey: 'parts.hem.variants.handkerchief', svgPath: 'dresses/maxi-dress/hem/handkerchief.svg' },
      ],
    },
    {
      id: 'slit',
      nameKey: 'parts.slit.name',
      required: false,
      layerOrder: 1,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.slit.variants.none', svgPath: 'dresses/maxi-dress/slit/none.svg' },
        { id: 'center', nameKey: 'parts.slit.variants.center', svgPath: 'dresses/maxi-dress/slit/center.svg' },
        { id: 'side', nameKey: 'parts.slit.variants.side', svgPath: 'dresses/maxi-dress/slit/side.svg' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'round',
      variants: [
        { id: 'round', nameKey: 'parts.neckline.variants.round', svgPath: 'dresses/maxi-dress/neckline/round.svg' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: 'dresses/maxi-dress/neckline/v-neck.svg' },
        { id: 'scoop', nameKey: 'parts.neckline.variants.scoop', svgPath: 'dresses/maxi-dress/neckline/scoop.svg' },
        { id: 'halter', nameKey: 'parts.neckline.variants.halter', svgPath: 'dresses/maxi-dress/neckline/halter.svg' },
        { id: 'strapless', nameKey: 'parts.neckline.variants.strapless', svgPath: 'dresses/maxi-dress/neckline/strapless.svg' },
        { id: 'sweetheart', nameKey: 'parts.neckline.variants.sweetheart', svgPath: 'dresses/maxi-dress/neckline/sweetheart.svg' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: 'dresses/maxi-dress/neckline/off-shoulder.svg' },
        { id: 'one-shoulder', nameKey: 'parts.neckline.variants.one-shoulder', svgPath: 'dresses/maxi-dress/neckline/one-shoulder.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'sleeveless',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: 'dresses/maxi-dress/sleeves/long.svg' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: 'dresses/maxi-dress/sleeves/short.svg' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: 'dresses/maxi-dress/sleeves/three-quarter.svg' },
        { id: 'flutter', nameKey: 'parts.sleeves.variants.flutter', svgPath: 'dresses/maxi-dress/sleeves/flutter.svg' },
        { id: 'cap', nameKey: 'parts.sleeves.variants.cap', svgPath: 'dresses/maxi-dress/sleeves/cap.svg' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: 'dresses/maxi-dress/sleeves/sleeveless.svg' },
      ],
    },
  ],
}
