import type { GarmentType } from '../../types'

export const shirtDress: GarmentType = {
  id: 'shirt-dress',
  categoryId: 'dresses',
  nameKey: 'garments.dresses.shirt-dress.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'waistline',
      nameKey: 'parts.waistline.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'natural',
      variants: [
        { id: 'natural', nameKey: 'parts.waistline.variants.natural', svgPath: 'dresses/shirt-dress/waistline/natural.svg' },
        { id: 'belted', nameKey: 'parts.waistline.variants.belted', svgPath: 'dresses/shirt-dress/waistline/belted.svg' },
        { id: 'cinched', nameKey: 'parts.waistline.variants.cinched', svgPath: 'dresses/shirt-dress/waistline/cinched.svg' },
        { id: 'drop', nameKey: 'parts.waistline.variants.drop', svgPath: 'dresses/shirt-dress/waistline/drop.svg' },
      ],
    },
    {
      id: 'skirt-length',
      nameKey: 'parts.skirt-length.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'knee',
      variants: [
        { id: 'above-knee', nameKey: 'parts.skirt-length.variants.above-knee', svgPath: 'dresses/shirt-dress/skirt-length/above-knee.svg' },
        { id: 'knee', nameKey: 'parts.skirt-length.variants.knee', svgPath: 'dresses/shirt-dress/skirt-length/knee.svg' },
        { id: 'midi', nameKey: 'parts.skirt-length.variants.midi', svgPath: 'dresses/shirt-dress/skirt-length/midi.svg' },
        { id: 'maxi', nameKey: 'parts.skirt-length.variants.maxi', svgPath: 'dresses/shirt-dress/skirt-length/maxi.svg' },
      ],
    },
    {
      id: 'pockets',
      nameKey: 'parts.pockets.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.pockets.variants.none', svgPath: 'dresses/shirt-dress/pockets/none.svg' },
        { id: 'chest', nameKey: 'parts.pockets.variants.chest', svgPath: 'dresses/shirt-dress/pockets/chest.svg' },
        { id: 'hip', nameKey: 'parts.pockets.variants.hip', svgPath: 'dresses/shirt-dress/pockets/hip.svg' },
      ],
    },
    {
      id: 'collar',
      nameKey: 'parts.collar.name',
      required: true,
      layerOrder: 4,
      defaultVariantId: 'classic',
      variants: [
        { id: 'classic', nameKey: 'parts.collar.variants.classic', svgPath: 'dresses/shirt-dress/collar/classic.svg' },
        { id: 'mandarin', nameKey: 'parts.collar.variants.mandarin', svgPath: 'dresses/shirt-dress/collar/mandarin.svg' },
        { id: 'band', nameKey: 'parts.collar.variants.band', svgPath: 'dresses/shirt-dress/collar/band.svg' },
        { id: 'peter-pan', nameKey: 'parts.collar.variants.peter-pan', svgPath: 'dresses/shirt-dress/collar/peter-pan.svg' },
        { id: 'button-down', nameKey: 'parts.collar.variants.button-down', svgPath: 'dresses/shirt-dress/collar/button-down.svg' },
        { id: 'camp', nameKey: 'parts.collar.variants.camp', svgPath: 'dresses/shirt-dress/collar/camp.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'long',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: 'dresses/shirt-dress/sleeves/long.svg' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: 'dresses/shirt-dress/sleeves/short.svg' },
        { id: 'rolled', nameKey: 'parts.sleeves.variants.rolled', svgPath: 'dresses/shirt-dress/sleeves/rolled.svg' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: 'dresses/shirt-dress/sleeves/three-quarter.svg' },
        { id: 'cap', nameKey: 'parts.sleeves.variants.cap', svgPath: 'dresses/shirt-dress/sleeves/cap.svg' },
      ],
    },
    {
      id: 'cuffs',
      nameKey: 'parts.cuffs.name',
      required: false,
      layerOrder: 6,
      defaultVariantId: 'barrel',
      variants: [
        { id: 'barrel', nameKey: 'parts.cuffs.variants.barrel', svgPath: 'dresses/shirt-dress/cuffs/barrel.svg' },
        { id: 'french', nameKey: 'parts.cuffs.variants.french', svgPath: 'dresses/shirt-dress/cuffs/french.svg' },
        { id: 'elastic', nameKey: 'parts.cuffs.variants.elastic', svgPath: 'dresses/shirt-dress/cuffs/elastic.svg' },
        { id: 'rolled', nameKey: 'parts.cuffs.variants.rolled', svgPath: 'dresses/shirt-dress/cuffs/rolled.svg' },
      ],
    },
  ],
}
