import type { GarmentType } from '../../types'

export const blouse: GarmentType = {
  id: 'blouse',
  categoryId: 'tops',
  nameKey: 'garments.tops.blouse.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'fit',
      nameKey: 'parts.fit.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'regular',
      variants: [
        { id: 'slim', nameKey: 'parts.fit.variants.slim', svgPath: 'tops/blouse/fit/slim.svg' },
        { id: 'regular', nameKey: 'parts.fit.variants.regular', svgPath: 'tops/blouse/fit/regular.svg' },
        { id: 'relaxed', nameKey: 'parts.fit.variants.relaxed', svgPath: 'tops/blouse/fit/relaxed.svg' },
        { id: 'oversized', nameKey: 'parts.fit.variants.oversized', svgPath: 'tops/blouse/fit/oversized.svg' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: 'tops/blouse/hem/straight.svg' },
        { id: 'curved', nameKey: 'parts.hem.variants.curved', svgPath: 'tops/blouse/hem/curved.svg' },
        { id: 'peplum', nameKey: 'parts.hem.variants.peplum', svgPath: 'tops/blouse/hem/peplum.svg' },
        { id: 'asymmetric', nameKey: 'parts.hem.variants.asymmetric', svgPath: 'tops/blouse/hem/asymmetric.svg' },
      ],
    },
    {
      id: 'closure',
      nameKey: 'parts.closure.name',
      required: true,
      layerOrder: 2,
      defaultVariantId: 'buttons',
      variants: [
        { id: 'buttons', nameKey: 'parts.closure.variants.buttons', svgPath: 'tops/blouse/closure/buttons.svg' },
        { id: 'hidden', nameKey: 'parts.closure.variants.hidden', svgPath: 'tops/blouse/closure/hidden.svg' },
        { id: 'tie', nameKey: 'parts.closure.variants.tie', svgPath: 'tops/blouse/closure/tie.svg' },
        { id: 'none', nameKey: 'parts.closure.variants.none', svgPath: 'tops/blouse/closure/none.svg' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'round',
      variants: [
        { id: 'round', nameKey: 'parts.neckline.variants.round', svgPath: 'tops/blouse/neckline/round.svg' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: 'tops/blouse/neckline/v-neck.svg' },
        { id: 'square', nameKey: 'parts.neckline.variants.square', svgPath: 'tops/blouse/neckline/square.svg' },
        { id: 'cowl', nameKey: 'parts.neckline.variants.cowl', svgPath: 'tops/blouse/neckline/cowl.svg' },
        { id: 'keyhole', nameKey: 'parts.neckline.variants.keyhole', svgPath: 'tops/blouse/neckline/keyhole.svg' },
        { id: 'tie-neck', nameKey: 'parts.neckline.variants.tie-neck', svgPath: 'tops/blouse/neckline/tie-neck.svg' },
        { id: 'ruffled', nameKey: 'parts.neckline.variants.ruffled', svgPath: 'tops/blouse/neckline/ruffled.svg' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: 'tops/blouse/neckline/off-shoulder.svg' },
      ],
    },
    {
      id: 'embellishments',
      nameKey: 'parts.embellishments.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.embellishments.variants.none', svgPath: 'tops/blouse/embellishments/none.svg' },
        { id: 'ruffle-front', nameKey: 'parts.embellishments.variants.ruffle-front', svgPath: 'tops/blouse/embellishments/ruffle-front.svg' },
        { id: 'lace-panel', nameKey: 'parts.embellishments.variants.lace-panel', svgPath: 'tops/blouse/embellishments/lace-panel.svg' },
        { id: 'pintucks', nameKey: 'parts.embellishments.variants.pintucks', svgPath: 'tops/blouse/embellishments/pintucks.svg' },
        { id: 'bow', nameKey: 'parts.embellishments.variants.bow', svgPath: 'tops/blouse/embellishments/bow.svg' },
        { id: 'pleats', nameKey: 'parts.embellishments.variants.pleats', svgPath: 'tops/blouse/embellishments/pleats.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'long',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: 'tops/blouse/sleeves/long.svg' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: 'tops/blouse/sleeves/short.svg' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: 'tops/blouse/sleeves/three-quarter.svg' },
        { id: 'puff', nameKey: 'parts.sleeves.variants.puff', svgPath: 'tops/blouse/sleeves/puff.svg' },
        { id: 'bishop', nameKey: 'parts.sleeves.variants.bishop', svgPath: 'tops/blouse/sleeves/bishop.svg' },
        { id: 'bell', nameKey: 'parts.sleeves.variants.bell', svgPath: 'tops/blouse/sleeves/bell.svg' },
        { id: 'flutter', nameKey: 'parts.sleeves.variants.flutter', svgPath: 'tops/blouse/sleeves/flutter.svg' },
        { id: 'balloon', nameKey: 'parts.sleeves.variants.balloon', svgPath: 'tops/blouse/sleeves/balloon.svg' },
        { id: 'cape', nameKey: 'parts.sleeves.variants.cape', svgPath: 'tops/blouse/sleeves/cape.svg' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: 'tops/blouse/sleeves/sleeveless.svg' },
      ],
    },
    {
      id: 'cuffs',
      nameKey: 'parts.cuffs.name',
      required: false,
      layerOrder: 6,
      defaultVariantId: 'barrel',
      variants: [
        { id: 'barrel', nameKey: 'parts.cuffs.variants.barrel', svgPath: 'tops/blouse/cuffs/barrel.svg' },
        { id: 'elastic', nameKey: 'parts.cuffs.variants.elastic', svgPath: 'tops/blouse/cuffs/elastic.svg' },
        { id: 'ruffle', nameKey: 'parts.cuffs.variants.ruffle', svgPath: 'tops/blouse/cuffs/ruffle.svg' },
        { id: 'tie', nameKey: 'parts.cuffs.variants.tie', svgPath: 'tops/blouse/cuffs/tie.svg' },
        { id: 'none', nameKey: 'parts.cuffs.variants.none', svgPath: 'tops/blouse/cuffs/none.svg' },
      ],
    },
  ],
}
