import type { GarmentType } from '../../types'

export const blouse: GarmentType = {
  id: 'blouse',
  categoryId: 'tops',
  nameKey: 'garments.tops.blouse.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'fit',
      nameKey: 'parts.fit.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'regular',
      variants: [
        { id: 'slim', nameKey: 'parts.fit.variants.slim', svgPath: '' },
        { id: 'regular', nameKey: 'parts.fit.variants.regular', svgPath: '' },
        { id: 'relaxed', nameKey: 'parts.fit.variants.relaxed', svgPath: '' },
        { id: 'oversized', nameKey: 'parts.fit.variants.oversized', svgPath: '' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight', nameKey: 'parts.hem.variants.straight', svgPath: '' },
        { id: 'curved', nameKey: 'parts.hem.variants.curved', svgPath: '' },
        { id: 'peplum', nameKey: 'parts.hem.variants.peplum', svgPath: '' },
        { id: 'asymmetric', nameKey: 'parts.hem.variants.asymmetric', svgPath: '' },
      ],
    },
    {
      id: 'closure',
      nameKey: 'parts.closure.name',
      required: true,
      layerOrder: 2,
      defaultVariantId: 'buttons',
      variants: [
        { id: 'buttons', nameKey: 'parts.closure.variants.buttons', svgPath: '' },
        { id: 'hidden', nameKey: 'parts.closure.variants.hidden', svgPath: '' },
        { id: 'tie', nameKey: 'parts.closure.variants.tie', svgPath: '' },
        { id: 'none', nameKey: 'parts.closure.variants.none', svgPath: '' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'round',
      variants: [
        { id: 'round', nameKey: 'parts.neckline.variants.round', svgPath: '' },
        { id: 'v-neck', nameKey: 'parts.neckline.variants.v-neck', svgPath: '' },
        { id: 'square', nameKey: 'parts.neckline.variants.square', svgPath: '' },
        { id: 'cowl', nameKey: 'parts.neckline.variants.cowl', svgPath: '' },
        { id: 'keyhole', nameKey: 'parts.neckline.variants.keyhole', svgPath: '' },
        { id: 'tie-neck', nameKey: 'parts.neckline.variants.tie-neck', svgPath: '' },
        { id: 'ruffled', nameKey: 'parts.neckline.variants.ruffled', svgPath: '' },
        { id: 'off-shoulder', nameKey: 'parts.neckline.variants.off-shoulder', svgPath: '' },
      ],
    },
    {
      id: 'embellishments',
      nameKey: 'parts.embellishments.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'none',
      variants: [
        { id: 'none', nameKey: 'parts.embellishments.variants.none', svgPath: '' },
        { id: 'ruffle-front', nameKey: 'parts.embellishments.variants.ruffle-front', svgPath: '' },
        { id: 'lace-panel', nameKey: 'parts.embellishments.variants.lace-panel', svgPath: '' },
        { id: 'pintucks', nameKey: 'parts.embellishments.variants.pintucks', svgPath: '' },
        { id: 'bow', nameKey: 'parts.embellishments.variants.bow', svgPath: '' },
        { id: 'pleats', nameKey: 'parts.embellishments.variants.pleats', svgPath: '' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'long',
      variants: [
        { id: 'long', nameKey: 'parts.sleeves.variants.long', svgPath: '' },
        { id: 'short', nameKey: 'parts.sleeves.variants.short', svgPath: '' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: '' },
        { id: 'puff', nameKey: 'parts.sleeves.variants.puff', svgPath: '' },
        { id: 'bishop', nameKey: 'parts.sleeves.variants.bishop', svgPath: '' },
        { id: 'bell', nameKey: 'parts.sleeves.variants.bell', svgPath: '' },
        { id: 'flutter', nameKey: 'parts.sleeves.variants.flutter', svgPath: '' },
        { id: 'balloon', nameKey: 'parts.sleeves.variants.balloon', svgPath: '' },
        { id: 'cape', nameKey: 'parts.sleeves.variants.cape', svgPath: '' },
        { id: 'sleeveless', nameKey: 'parts.sleeves.variants.sleeveless', svgPath: '' },
      ],
    },
    {
      id: 'cuffs',
      nameKey: 'parts.cuffs.name',
      required: false,
      layerOrder: 6,
      defaultVariantId: 'barrel',
      variants: [
        { id: 'barrel', nameKey: 'parts.cuffs.variants.barrel', svgPath: '' },
        { id: 'elastic', nameKey: 'parts.cuffs.variants.elastic', svgPath: '' },
        { id: 'ruffle', nameKey: 'parts.cuffs.variants.ruffle', svgPath: '' },
        { id: 'tie', nameKey: 'parts.cuffs.variants.tie', svgPath: '' },
        { id: 'none', nameKey: 'parts.cuffs.variants.none', svgPath: '' },
      ],
    },
  ],
}
