import type { GarmentType } from '../../types'

export const shirt: GarmentType = {
  id: 'shirt',
  categoryId: 'tops',
  nameKey: 'garments.tops.shirt.name',
  svgViewBox: '0 0 200 300',
  parts: [
    {
      id: 'body',
      nameKey: 'parts.body.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.body.variants.standard', svgPath: 'tops/shirt/body/standard.svg' },
      ],
    },
    {
      id: 'fit',
      nameKey: 'parts.fit.name',
      required: true,
      layerOrder: 0,
      defaultVariantId: 'regular',
      variants: [
        { id: 'slim',     nameKey: 'parts.fit.variants.slim',     svgPath: 'tops/shirt/fit/slim.svg' },
        { id: 'regular',  nameKey: 'parts.fit.variants.regular',  svgPath: 'tops/shirt/fit/regular.svg' },
        { id: 'relaxed',  nameKey: 'parts.fit.variants.relaxed',  svgPath: 'tops/shirt/fit/relaxed.svg' },
        { id: 'oversized', nameKey: 'parts.fit.variants.oversized', svgPath: 'tops/shirt/fit/oversized.svg' },
      ],
    },
    {
      id: 'yoke',
      nameKey: 'parts.yoke.name',
      required: false,
      layerOrder: 1,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.yoke.variants.standard', svgPath: 'tops/shirt/yoke/standard.svg' },
        { id: 'split',    nameKey: 'parts.yoke.variants.split',    svgPath: 'tops/shirt/yoke/split.svg' },
        { id: 'none',     nameKey: 'parts.yoke.variants.none',     svgPath: '' },
      ],
    },
    {
      id: 'hem',
      nameKey: 'parts.hem.name',
      required: true,
      layerOrder: 1,
      defaultVariantId: 'straight',
      variants: [
        { id: 'straight',    nameKey: 'parts.hem.variants.straight',    svgPath: 'tops/shirt/hem/straight.svg' },
        { id: 'curved',      nameKey: 'parts.hem.variants.curved',      svgPath: 'tops/shirt/hem/curved.svg' },
        { id: 'split',       nameKey: 'parts.hem.variants.split',       svgPath: 'tops/shirt/hem/split.svg' },
        { id: 'asymmetric',  nameKey: 'parts.hem.variants.asymmetric',  svgPath: 'tops/shirt/hem/asymmetric.svg' },
      ],
    },
    {
      id: 'placket',
      nameKey: 'parts.placket.name',
      required: true,
      layerOrder: 2,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.placket.variants.standard', svgPath: 'tops/shirt/placket/standard.svg' },
        { id: 'hidden',   nameKey: 'parts.placket.variants.hidden',   svgPath: 'tops/shirt/placket/hidden.svg' },
        { id: 'french',   nameKey: 'parts.placket.variants.french',   svgPath: 'tops/shirt/placket/french.svg' },
        { id: 'half',     nameKey: 'parts.placket.variants.half',     svgPath: 'tops/shirt/placket/half.svg' },
      ],
    },
    {
      id: 'neckline',
      nameKey: 'parts.neckline.name',
      required: true,
      layerOrder: 3,
      defaultVariantId: 'standard',
      variants: [
        { id: 'standard', nameKey: 'parts.neckline.variants.standard', svgPath: 'tops/shirt/neckline/standard.svg' },
        { id: 'v-neck',   nameKey: 'parts.neckline.variants.v-neck',   svgPath: 'tops/shirt/neckline/v-neck.svg' },
        { id: 'crew',     nameKey: 'parts.neckline.variants.crew',     svgPath: 'tops/shirt/neckline/crew.svg' },
        { id: 'scoop',    nameKey: 'parts.neckline.variants.scoop',    svgPath: 'tops/shirt/neckline/scoop.svg' },
        { id: 'henley',   nameKey: 'parts.neckline.variants.henley',   svgPath: 'tops/shirt/neckline/henley.svg' },
        { id: 'boat',     nameKey: 'parts.neckline.variants.boat',     svgPath: 'tops/shirt/neckline/boat.svg' },
      ],
    },
    {
      id: 'pockets',
      nameKey: 'parts.pockets.name',
      required: false,
      layerOrder: 3,
      defaultVariantId: 'none',
      variants: [
        { id: 'none',          nameKey: 'parts.pockets.variants.none',          svgPath: '' },
        { id: 'chest-single',  nameKey: 'parts.pockets.variants.chest-single',  svgPath: 'tops/shirt/pockets/chest-single.svg' },
        { id: 'chest-double',  nameKey: 'parts.pockets.variants.chest-double',  svgPath: 'tops/shirt/pockets/chest-double.svg' },
        { id: 'flap',          nameKey: 'parts.pockets.variants.flap',          svgPath: 'tops/shirt/pockets/flap.svg' },
        { id: 'welt',          nameKey: 'parts.pockets.variants.welt',          svgPath: 'tops/shirt/pockets/welt.svg' },
      ],
    },
    {
      id: 'collar',
      nameKey: 'parts.collar.name',
      required: true,
      layerOrder: 4,
      defaultVariantId: 'classic',
      variants: [
        { id: 'classic',     nameKey: 'parts.collar.variants.classic',     svgPath: 'tops/shirt/collar/classic.svg' },
        { id: 'mandarin',    nameKey: 'parts.collar.variants.mandarin',    svgPath: 'tops/shirt/collar/mandarin.svg' },
        { id: 'mao',         nameKey: 'parts.collar.variants.mao',         svgPath: 'tops/shirt/collar/mao.svg' },
        { id: 'button-down', nameKey: 'parts.collar.variants.button-down', svgPath: 'tops/shirt/collar/button-down.svg' },
        { id: 'peter-pan',   nameKey: 'parts.collar.variants.peter-pan',   svgPath: 'tops/shirt/collar/peter-pan.svg' },
        { id: 'wing',        nameKey: 'parts.collar.variants.wing',        svgPath: 'tops/shirt/collar/wing.svg' },
        { id: 'band',        nameKey: 'parts.collar.variants.band',        svgPath: 'tops/shirt/collar/band.svg' },
        { id: 'club',        nameKey: 'parts.collar.variants.club',        svgPath: 'tops/shirt/collar/club.svg' },
      ],
    },
    {
      id: 'sleeves',
      nameKey: 'parts.sleeves.name',
      required: true,
      layerOrder: 5,
      defaultVariantId: 'long',
      variants: [
        { id: 'long',          nameKey: 'parts.sleeves.variants.long',          svgPath: 'tops/shirt/sleeves/long.svg' },
        { id: 'short',         nameKey: 'parts.sleeves.variants.short',         svgPath: 'tops/shirt/sleeves/short.svg' },
        { id: 'three-quarter', nameKey: 'parts.sleeves.variants.three-quarter', svgPath: 'tops/shirt/sleeves/three-quarter.svg' },
        { id: 'rolled',        nameKey: 'parts.sleeves.variants.rolled',        svgPath: 'tops/shirt/sleeves/rolled.svg' },
        { id: 'raglan',        nameKey: 'parts.sleeves.variants.raglan',        svgPath: 'tops/shirt/sleeves/raglan.svg' },
        { id: 'puff',          nameKey: 'parts.sleeves.variants.puff',          svgPath: 'tops/shirt/sleeves/puff.svg' },
        { id: 'bishop',        nameKey: 'parts.sleeves.variants.bishop',        svgPath: 'tops/shirt/sleeves/bishop.svg' },
        { id: 'cap',           nameKey: 'parts.sleeves.variants.cap',           svgPath: 'tops/shirt/sleeves/cap.svg' },
      ],
    },
    {
      id: 'cuffs',
      nameKey: 'parts.cuffs.name',
      required: false,
      layerOrder: 6,
      defaultVariantId: 'barrel',
      variants: [
        { id: 'barrel',      nameKey: 'parts.cuffs.variants.barrel',      svgPath: 'tops/shirt/cuffs/barrel.svg' },
        { id: 'french',      nameKey: 'parts.cuffs.variants.french',      svgPath: 'tops/shirt/cuffs/french.svg' },
        { id: 'convertible', nameKey: 'parts.cuffs.variants.convertible', svgPath: 'tops/shirt/cuffs/convertible.svg' },
        { id: 'turnback',    nameKey: 'parts.cuffs.variants.turnback',    svgPath: 'tops/shirt/cuffs/turnback.svg' },
        { id: 'ribbed',      nameKey: 'parts.cuffs.variants.ribbed',      svgPath: 'tops/shirt/cuffs/ribbed.svg' },
        { id: 'elastic',     nameKey: 'parts.cuffs.variants.elastic',     svgPath: 'tops/shirt/cuffs/elastic.svg' },
      ],
    },
  ],
}
